### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by PTT1230** [PTT1230/protospace-38221#1]
【依頼】ProtoSpace挙動確認

**Comment by PTT1230** [comment]
https://protospace-38221.herokuapp.com/

**Comment by yusuketono** [comment]
@PTT1230 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
##### プロトタイプ投稿機能
- [x] **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること**
エラー画面に遷移してしまうので、そのページに留まるように修正しましょう。

##### プロトタイプ一覧表示機能
- [x] **プロトタイプ毎に、画像・プロトタイプ名・キャッチコピー・投稿者名の、4つの情報について表示できること**
投稿者ではない名称が表示されてしまいます。
![スクリーンショット 2022-07-25 14 46 12](https://user-images.githubusercontent.com/51428519/180706764-e92504f5-0089-40ec-b268-91020ea3f5bd.png)

##### コメント機能
- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
エラー画面に遷移してしまうので、そのページに留まるように修正しましょう。

##### その他
- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされること**
他のユーザーのプロトタイプ編集ページに遷移できてしまうので、トップページにリダイレクトするよう修正しましょう。
```
【チェック方法】
先ず、ユーザーAで投稿したプロトタイプの編集ページURLをコピー。
次に、ユーザーBでログインし、そのURLを直接入力した際に、トップページへリダイレクトされれば正常な挙動。
```


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by PTT1230** [comment]
rails routesはどう確認すれば良いのでしょうか？

**Comment by yusuketono** [comment]
@PTT1230 さん、再度ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

なお、rails routesの確認方法に関するご質問は技術的な内容となりますので、
恐れ入りますが、テックコネクトにてご質問いただけますと幸いです。
